# -*- coding: utf-8 -*-
"""retentioniq_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYBNdvg4pcFAwteh6OuqoqEn7CWarAcX
"""

import pandas as pd
import numpy as np

accounts = pd.read_csv("ravenstack_accounts.csv")
subscriptions = pd.read_csv("ravenstack_subscriptions.csv")
feature_usage = pd.read_csv("ravenstack_feature_usage.csv")
support_tickets = pd.read_csv("ravenstack_support_tickets.csv")
churn_events = pd.read_csv("ravenstack_churn_events.csv")

print("All 5 datasets loaded successfully!")

datasets = {
    "Accounts": accounts,
    "Subscriptions": subscriptions,
    "Feature Usage": feature_usage,
    "Support Tickets": support_tickets,
    "Churn Events": churn_events
}

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("\nColumn names:")
    print(df.columns.tolist())
    print("\nMissing values:")
    print(df.isna().sum())

# STEP 3 — ID and relationship validation

print("=" * 70)
print("DUPLICATE CHECK")
print("=" * 70)

for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} completely duplicated rows")


print("\n" + "=" * 70)
print("UNIQUE ID CHECK")
print("=" * 70)

print("Accounts:")
print("  Rows:", len(accounts))
print("  Unique account_id:", accounts["account_id"].nunique())

print("\nSubscriptions:")
print("  Rows:", len(subscriptions))
print("  Unique subscription_id:", subscriptions["subscription_id"].nunique())

print("\nFeature Usage:")
print("  Rows:", len(feature_usage))
print("  Unique usage_id:", feature_usage["usage_id"].nunique())

print("\nSupport Tickets:")
print("  Rows:", len(support_tickets))
print("  Unique ticket_id:", support_tickets["ticket_id"].nunique())

print("\nChurn Events:")
print("  Rows:", len(churn_events))
print("  Unique churn_event_id:", churn_events["churn_event_id"].nunique())


print("\n" + "=" * 70)
print("RELATIONSHIP / FOREIGN KEY CHECK")
print("=" * 70)

print(
    "Subscriptions → Accounts:",
    (~subscriptions["account_id"].isin(accounts["account_id"])).sum(),
    "invalid account IDs"
)

print(
    "Support Tickets → Accounts:",
    (~support_tickets["account_id"].isin(accounts["account_id"])).sum(),
    "invalid account IDs"
)

print(
    "Churn Events → Accounts:",
    (~churn_events["account_id"].isin(accounts["account_id"])).sum(),
    "invalid account IDs"
)

print(
    "Feature Usage → Subscriptions:",
    (~feature_usage["subscription_id"].isin(subscriptions["subscription_id"])).sum(),
    "invalid subscription IDs"
)

# STEP 4 — Investigate duplicate usage IDs

duplicate_usage_ids = feature_usage[
    feature_usage["usage_id"].duplicated(keep=False)
].sort_values("usage_id")

print("Rows involved in repeated usage IDs:", len(duplicate_usage_ids))
print("Number of repeated usage IDs:", duplicate_usage_ids["usage_id"].nunique())

duplicate_usage_ids

# STEP 4B — Check for duplicate usage events

usage_event_columns = [
    "subscription_id",
    "usage_date",
    "feature_name",
    "usage_count",
    "usage_duration_secs",
    "error_count",
    "is_beta_feature"
]

duplicate_events = feature_usage[
    feature_usage.duplicated(
        subset=usage_event_columns,
        keep=False
    )
]

print("Potentially duplicated usage events:", len(duplicate_events))

if len(duplicate_events) > 0:
    print("\nNumber of duplicate event groups:",
          duplicate_events.groupby(usage_event_columns).ngroups)

    display(duplicate_events.sort_values(usage_event_columns))
else:
    print("No duplicated usage events found.")

# STEP 5 — Date validation

# Convert date columns to datetime
accounts["signup_date"] = pd.to_datetime(accounts["signup_date"])

subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"])
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"])

feature_usage["usage_date"] = pd.to_datetime(feature_usage["usage_date"])

support_tickets["submitted_at"] = pd.to_datetime(support_tickets["submitted_at"])
support_tickets["closed_at"] = pd.to_datetime(support_tickets["closed_at"])

churn_events["churn_date"] = pd.to_datetime(churn_events["churn_date"])


print("=" * 70)
print("DATE RANGES")
print("=" * 70)

print("\nAccounts signup dates:")
print(accounts["signup_date"].min(), "to", accounts["signup_date"].max())

print("\nSubscription start dates:")
print(subscriptions["start_date"].min(), "to", subscriptions["start_date"].max())

print("\nSubscription end dates:")
print(subscriptions["end_date"].min(), "to", subscriptions["end_date"].max())

print("\nFeature usage dates:")
print(feature_usage["usage_date"].min(), "to", feature_usage["usage_date"].max())

print("\nSupport ticket dates:")
print(support_tickets["submitted_at"].min(), "to", support_tickets["submitted_at"].max())

print("\nChurn dates:")
print(churn_events["churn_date"].min(), "to", churn_events["churn_date"].max())


print("\n" + "=" * 70)
print("DATE LOGIC CHECKS")
print("=" * 70)

# Subscription ending before it starts
invalid_subscription_dates = subscriptions[
    subscriptions["end_date"].notna() &
    (subscriptions["end_date"] < subscriptions["start_date"])
]

print(
    "\nSubscriptions ending before starting:",
    len(invalid_subscription_dates)
)

# Support ticket closed before submitted
invalid_support_dates = support_tickets[
    support_tickets["closed_at"] < support_tickets["submitted_at"]
]

print(
    "Support tickets closed before submission:",
    len(invalid_support_dates)
)

# Usage before subscription starts
usage_with_subscription_dates = feature_usage.merge(
    subscriptions[["subscription_id", "start_date", "end_date"]],
    on="subscription_id",
    how="left"
)

usage_before_start = usage_with_subscription_dates[
    usage_with_subscription_dates["usage_date"] <
    usage_with_subscription_dates["start_date"]
]

print(
    "Usage records before subscription start:",
    len(usage_before_start)
)

# Usage after subscription ended
usage_after_end = usage_with_subscription_dates[
    usage_with_subscription_dates["end_date"].notna() &
    (usage_with_subscription_dates["usage_date"] >
     usage_with_subscription_dates["end_date"])
]

print(
    "Usage records after subscription end:",
    len(usage_after_end)
)

# STEP 5A — Investigate subscription periods

print("Subscription status:")
print(subscriptions["churn_flag"].value_counts())

print("\nBilling frequency:")
print(subscriptions["billing_frequency"].value_counts())

print("\nAuto-renewal:")
print(subscriptions["auto_renew_flag"].value_counts())

print("\nUpgrade flags:")
print(subscriptions["upgrade_flag"].value_counts())

print("\nDowngrade flags:")
print(subscriptions["downgrade_flag"].value_counts())

# How many subscriptions are active vs ended?

active_subscriptions = subscriptions["end_date"].isna().sum()
ended_subscriptions = subscriptions["end_date"].notna().sum()

print("Active subscriptions:", active_subscriptions)
print("Ended subscriptions:", ended_subscriptions)

# Check how many subscriptions each account has

subscription_counts = subscriptions.groupby("account_id").size()

print("Minimum subscriptions per account:", subscription_counts.min())
print("Maximum subscriptions per account:", subscription_counts.max())
print("Average subscriptions per account:", subscription_counts.mean())

print("\nAccounts with more than one subscription:",
      (subscription_counts > 1).sum())

# STEP 6 — Investigate usage date anomalies

# Merge usage with the subscription dates
usage_check = feature_usage.merge(
    subscriptions[
        ["subscription_id", "account_id", "start_date", "end_date",
         "churn_flag"]
    ],
    on="subscription_id",
    how="left"
)

# Calculate how far the usage date is from subscription start/end
usage_check["days_before_start"] = (
    usage_check["start_date"] - usage_check["usage_date"]
).dt.days

usage_check["days_after_end"] = (
    usage_check["usage_date"] - usage_check["end_date"]
).dt.days

print("Usage records before subscription start:",
      (usage_check["days_before_start"] > 0).sum())

print("Usage records after subscription end:",
      (usage_check["days_after_end"] > 0).sum())

print("\nDays before subscription start:")
print(
    usage_check.loc[
        usage_check["days_before_start"] > 0,
        "days_before_start"
    ].describe()
)

print("\nDays after subscription end:")
print(
    usage_check.loc[
        usage_check["days_after_end"] > 0,
        "days_after_end"
    ].describe()
)

# STEP 7 — Numerical and revenue validation

print("=" * 70)
print("SUBSCRIPTION VALUES")
print("=" * 70)

print("\nSeats:")
print(subscriptions["seats"].describe())

print("\nMRR:")
print(subscriptions["mrr_amount"].describe())

print("\nARR:")
print(subscriptions["arr_amount"].describe())

print("\nChecking MRR <= 0:")
print((subscriptions["mrr_amount"] <= 0).sum())

print("\nChecking ARR <= 0:")
print((subscriptions["arr_amount"] <= 0).sum())

print("\nChecking seats <= 0:")
print((subscriptions["seats"] <= 0).sum())


print("\n" + "=" * 70)
print("FEATURE USAGE")
print("=" * 70)

print("\nUsage count:")
print(feature_usage["usage_count"].describe())

print("\nUsage duration (seconds):")
print(feature_usage["usage_duration_secs"].describe())

print("\nError count:")
print(feature_usage["error_count"].describe())

print("\nNegative usage count:",
      (feature_usage["usage_count"] < 0).sum())

print("Negative duration:",
      (feature_usage["usage_duration_secs"] < 0).sum())

print("Negative errors:",
      (feature_usage["error_count"] < 0).sum())


print("\n" + "=" * 70)
print("SUPPORT")
print("=" * 70)

print("\nResolution time:")
print(support_tickets["resolution_time_hours"].describe())

print("\nFirst response time:")
print(support_tickets["first_response_time_minutes"].describe())

print("\nSatisfaction score:")
print(support_tickets["satisfaction_score"].describe())

print("\nNegative resolution times:",
      (support_tickets["resolution_time_hours"] < 0).sum())

print("Negative response times:",
      (support_tickets["first_response_time_minutes"] < 0).sum())


print("\n" + "=" * 70)
print("CHURN / REFUNDS")
print("=" * 70)

print("\nRefund amount:")
print(churn_events["refund_amount_usd"].describe())

print("\nNegative refunds:",
      (churn_events["refund_amount_usd"] < 0).sum())

# STEP 8 — Churn consistency analysis

print("=" * 70)
print("ACCOUNT-LEVEL CHURN")
print("=" * 70)

print(accounts["churn_flag"].value_counts())

print("\n" + "=" * 70)
print("SUBSCRIPTION-LEVEL CHURN")
print("=" * 70)

print(subscriptions["churn_flag"].value_counts())

print("\n" + "=" * 70)
print("CHURN EVENTS")
print("=" * 70)

print("Total churn events:", len(churn_events))
print(
    "Unique accounts with churn events:",
    churn_events["account_id"].nunique()
)

print(
    "\nReactivation events:",
    churn_events["is_reactivation"].sum()
)

print(
    "Regular churn events:",
    (~churn_events["is_reactivation"]).sum()
)


# Accounts marked as churned
churned_accounts = set(
    accounts.loc[accounts["churn_flag"], "account_id"]
)

# Accounts appearing in churn events
event_accounts = set(churn_events["account_id"])

print("\n" + "=" * 70)
print("ACCOUNT vs CHURN EVENT COMPARISON")
print("=" * 70)

print(
    "Accounts marked churned but with no churn event:",
    len(churned_accounts - event_accounts)
)

print(
    "Accounts with churn events but currently NOT marked churned:",
    len(event_accounts - churned_accounts)
)


# Subscription churn vs account churn
subscription_churn_accounts = set(
    subscriptions.loc[
        subscriptions["churn_flag"],
        "account_id"
    ]
)

print("\n" + "=" * 70)
print("SUBSCRIPTION vs ACCOUNT CHURN")
print("=" * 70)

print(
    "Accounts with churned subscriptions:",
    len(subscription_churn_accounts)
)

print(
    "Accounts marked churned:",
    len(churned_accounts)
)

print(
    "Accounts with churned subscriptions but account not churned:",
    len(subscription_churn_accounts - churned_accounts)
)

print(
    "Accounts marked churned but no churned subscription:",
    len(churned_accounts - subscription_churn_accounts)
)

import os

os.makedirs("02_Cleaned_Data", exist_ok=True)

print("Cleaned data folder created.")

import re

def clean_column_names(df):
    df = df.copy()
    df.columns = [
        re.sub(r'[^a-zA-Z0-9]+', '_', col).strip('_').lower()
        for col in df.columns
    ]
    return df


accounts = clean_column_names(accounts)
subscriptions = clean_column_names(subscriptions)
feature_usage = clean_column_names(feature_usage)
support_tickets = clean_column_names(support_tickets)
churn_events = clean_column_names(churn_events)

for name, df in datasets.items():
    print(name, ":", df.columns.tolist())

date_columns = {
    "accounts": ["signup_date"],
    "subscriptions": ["start_date", "end_date"],
    "feature_usage": ["usage_date"],
    "support_tickets": ["submitted_at", "closed_at"],
    "churn_events": ["churn_date"]
}

dataframes = {
    "accounts": accounts,
    "subscriptions": subscriptions,
    "feature_usage": feature_usage,
    "support_tickets": support_tickets,
    "churn_events": churn_events
}

for name, columns in date_columns.items():
    for column in columns:
        dataframes[name][column] = pd.to_datetime(
            dataframes[name][column],
            errors="coerce"
        )

print("Date columns standardized successfully.")

churn_events["feedback_text"] = (
    churn_events["feedback_text"]
    .fillna("No feedback provided")
)

boolean_columns = {
    "accounts": ["is_trial", "churn_flag"],
    "subscriptions": [
        "is_trial",
        "upgrade_flag",
        "downgrade_flag",
        "churn_flag",
        "auto_renew_flag"
    ],
    "feature_usage": ["is_beta_feature"],
    "support_tickets": ["escalation_flag"],
    "churn_events": [
        "preceding_upgrade_flag",
        "preceding_downgrade_flag",
        "is_reactivation"
    ]
}

for name, columns in boolean_columns.items():
    for column in columns:
        dataframes[name][column] = (
            dataframes[name][column]
            .astype(bool)
        )

print("Boolean fields standardized.")

for name, df in dataframes.items():
    file_path = f"02_Cleaned_Data/cleaned_{name}.csv"
    df.to_csv(file_path, index=False)
    print("Saved:", file_path)

# STEP 10 — Customer profile

print("=" * 70)
print("CUSTOMER PROFILE")
print("=" * 70)

print("\nIndustry distribution:")
print(accounts["industry"].value_counts())

print("\nCountry distribution:")
print(accounts["country"].value_counts())

print("\nPlan tier distribution:")
print(accounts["plan_tier"].value_counts())

print("\nTrial vs non-trial:")
print(accounts["is_trial"].value_counts())

print("\nChurn status:")
print(accounts["churn_flag"].value_counts())

print("\nSeats:")
print(accounts["seats"].describe())

# Subscription profile

print("=" * 70)
print("SUBSCRIPTION PROFILE")
print("=" * 70)

print("\nPlan tier:")
print(subscriptions["plan_tier"].value_counts())

print("\nBilling frequency:")
print(subscriptions["billing_frequency"].value_counts())

print("\nSubscription churn:")
print(subscriptions["churn_flag"].value_counts())

print("\nTrial subscriptions:")
print(subscriptions["is_trial"].value_counts())

print("\nAuto renew:")
print(subscriptions["auto_renew_flag"].value_counts())

print("\nUpgrades:")
print(subscriptions["upgrade_flag"].value_counts())

print("\nDowngrades:")
print(subscriptions["downgrade_flag"].value_counts())

print("=" * 70)
print("REVENUE ANALYSIS")
print("=" * 70)

# Overall revenue metrics
print("\nOverall Revenue Metrics:")
print("Total MRR: $", round(subscriptions["mrr_amount"].sum(), 2))
print("Total ARR: $", round(subscriptions["arr_amount"].sum(), 2))
print("Average MRR per subscription: $", round(subscriptions["mrr_amount"].mean(), 2))
print("Median MRR per subscription: $", round(subscriptions["mrr_amount"].median(), 2))

# Revenue by plan
print("\nMRR by Plan Tier:")
print(
    subscriptions.groupby("plan_tier")["mrr_amount"]
    .agg(["sum", "mean", "count"])
    .sort_values("sum", ascending=False)
)

# ARR by plan
print("\nARR by Plan Tier:")
print(
    subscriptions.groupby("plan_tier")["arr_amount"]
    .agg(["sum", "mean", "count"])
    .sort_values("sum", ascending=False)
)

# Revenue by billing frequency
print("\nMRR by Billing Frequency:")
print(
    subscriptions.groupby("billing_frequency")["mrr_amount"]
    .agg(["sum", "mean", "count"])
    .sort_values("sum", ascending=False)
)

# Revenue from churned subscriptions
churned_subs = subscriptions[subscriptions["churn_flag"] == True]

print("\nChurned Subscription Revenue:")
print("Churned subscriptions:", len(churned_subs))
print("MRR associated with churned subscriptions: $",
      round(churned_subs["mrr_amount"].sum(), 2))
print("ARR associated with churned subscriptions: $",
      round(churned_subs["arr_amount"].sum(), 2))

# Active subscriptions
active_subs = subscriptions[subscriptions["churn_flag"] == False]

print("\nActive Subscription Revenue:")
print("Active subscriptions:", len(active_subs))
print("Active MRR: $",
      round(active_subs["mrr_amount"].sum(), 2))
print("Active ARR: $",
      round(active_subs["arr_amount"].sum(), 2))

print("=" * 70)
print("CHURN ANALYSIS")
print("=" * 70)

# 1. Overall account churn
print("\nOverall Account Churn:")
print(accounts["churn_flag"].value_counts())

account_churn_rate = accounts["churn_flag"].mean() * 100
print("Account Churn Rate:", round(account_churn_rate, 2), "%")


# 2. Churn by plan tier
print("\nChurn by Plan Tier:")

plan_churn = (
    accounts.groupby("plan_tier")["churn_flag"]
    .agg(["count", "sum", "mean"])
)

plan_churn["churn_rate_%"] = plan_churn["mean"] * 100
plan_churn = plan_churn.drop(columns=["mean"])

print(plan_churn.sort_values("churn_rate_%", ascending=False))


# 3. Churn by industry
print("\nChurn by Industry:")

industry_churn = (
    accounts.groupby("industry")["churn_flag"]
    .agg(["count", "sum", "mean"])
)

industry_churn["churn_rate_%"] = industry_churn["mean"] * 100
industry_churn = industry_churn.drop(columns=["mean"])

print(industry_churn.sort_values("churn_rate_%", ascending=False))


# 4. Churn by trial status
print("\nChurn by Trial Status:")

trial_churn = (
    accounts.groupby("is_trial")["churn_flag"]
    .agg(["count", "sum", "mean"])
)

trial_churn["churn_rate_%"] = trial_churn["mean"] * 100
trial_churn = trial_churn.drop(columns=["mean"])

print(trial_churn)


# 5. Churn by referral source
print("\nChurn by Referral Source:")

referral_churn = (
    accounts.groupby("referral_source")["churn_flag"]
    .agg(["count", "sum", "mean"])
)

referral_churn["churn_rate_%"] = referral_churn["mean"] * 100
referral_churn = referral_churn.drop(columns=["mean"])

print(referral_churn.sort_values("churn_rate_%", ascending=False))


# 6. Churn by number of seats
print("\nAverage Seats — Churned vs Active:")

print(
    accounts.groupby("churn_flag")["seats"]
    .agg(["count", "mean", "median"])
)


# 7. Subscription-level churn
print("\nSubscription-Level Churn:")

subscription_churn_rate = subscriptions["churn_flag"].mean() * 100

print("Total subscriptions:", len(subscriptions))
print("Churned subscriptions:", subscriptions["churn_flag"].sum())
print("Subscription churn rate:",
      round(subscription_churn_rate, 2), "%")


# 8. Subscription churn by plan
print("\nSubscription Churn by Plan:")

subscription_plan_churn = (
    subscriptions.groupby("plan_tier")["churn_flag"]
    .agg(["count", "sum", "mean"])
)

subscription_plan_churn["churn_rate_%"] = (
    subscription_plan_churn["mean"] * 100
)

subscription_plan_churn = subscription_plan_churn.drop(columns=["mean"])

print(
    subscription_plan_churn
    .sort_values("churn_rate_%", ascending=False)
)

print("=" * 70)
print("PRODUCT USAGE & ENGAGEMENT ANALYSIS")
print("=" * 70)

# 1. Overall usage
print("\nOverall Usage:")
print("Total usage records:", len(feature_usage))
print("Unique accounts with usage:",
      subscriptions["account_id"].nunique())
print("Unique features used:",
      feature_usage["feature_name"].nunique())

print("\nUsage Count:")
print(feature_usage["usage_count"].describe())

print("\nUsage Duration (seconds):")
print(feature_usage["usage_duration_secs"].describe())

print("\nError Count:")
print(feature_usage["error_count"].describe())


# 2. Most-used features
print("\nMost Used Features:")

feature_summary = (
    feature_usage.groupby("feature_name")
    .agg(
        usage_events=("usage_id", "count"),
        total_usage=("usage_count", "sum"),
        total_duration_secs=("usage_duration_secs", "sum"),
        total_errors=("error_count", "sum")
    )
    .sort_values("total_usage", ascending=False)
)

print(feature_summary)


# 3. Usage aggregated to account level
account_usage = (
    feature_usage
    .merge(
        subscriptions[["subscription_id", "account_id"]],
        on="subscription_id",
        how="left"
    )
    .groupby("account_id")
    .agg(
        usage_events=("usage_id", "count"),
        total_usage=("usage_count", "sum"),
        total_duration_secs=("usage_duration_secs", "sum"),
        total_errors=("error_count", "sum"),
        features_used=("feature_name", "nunique")
    )
    .reset_index()
)

print("\nAccount-Level Usage:")
print(account_usage.describe())


# 4. Connect usage with churn
usage_churn = account_usage.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

print("\nUsage — Churned vs Active Customers:")

print(
    usage_churn.groupby("churn_flag")[
        [
            "usage_events",
            "total_usage",
            "total_duration_secs",
            "total_errors",
            "features_used"
        ]
    ].mean()
)


# 5. Median comparison
print("\nMedian Usage — Churned vs Active:")

print(
    usage_churn.groupby("churn_flag")[
        [
            "usage_events",
            "total_usage",
            "total_duration_secs",
            "total_errors",
            "features_used"
        ]
    ].median()
)


# 6. Beta feature usage
print("\nBeta Feature Usage:")

print(
    feature_usage.groupby("is_beta_feature")[
        ["usage_count", "usage_duration_secs", "error_count"]
    ].mean()
)

print("=" * 70)
print("SUPPORT & CUSTOMER EXPERIENCE ANALYSIS")
print("=" * 70)

# 1. Overall support metrics
print("\nOverall Support Metrics:")

print("Total tickets:", len(support_tickets))
print("Unique customers with tickets:",
      support_tickets["account_id"].nunique())

print("\nResolution Time (hours):")
print(support_tickets["resolution_time_hours"].describe())

print("\nFirst Response Time (minutes):")
print(support_tickets["first_response_time_minutes"].describe())

print("\nSatisfaction Score:")
print(support_tickets["satisfaction_score"].describe())


# 2. Ticket priority distribution
print("\nTicket Priority:")
print(support_tickets["priority"].value_counts())


# 3. Escalation rate
print("\nEscalation:")
print(support_tickets["escalation_flag"].value_counts())

escalation_rate = support_tickets["escalation_flag"].mean() * 100
print("Overall Escalation Rate:",
      round(escalation_rate, 2), "%")


# 4. Aggregate support metrics at account level
account_support = (
    support_tickets
    .groupby("account_id")
    .agg(
        total_tickets=("ticket_id", "count"),
        avg_resolution_hours=("resolution_time_hours", "mean"),
        avg_first_response_minutes=("first_response_time_minutes", "mean"),
        avg_satisfaction=("satisfaction_score", "mean"),
        escalated_tickets=("escalation_flag", "sum")
    )
    .reset_index()
)

# Calculate escalation rate per customer
account_support["escalation_rate"] = (
    account_support["escalated_tickets"] /
    account_support["total_tickets"]
)

print("\nAccount-Level Support Metrics:")
print(account_support.describe())


# 5. Merge support with customer churn
support_churn = account_support.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

print("\nSupport Metrics — Churned vs Active:")

print(
    support_churn.groupby("churn_flag")[
        [
            "total_tickets",
            "avg_resolution_hours",
            "avg_first_response_minutes",
            "avg_satisfaction",
            "escalated_tickets",
            "escalation_rate"
        ]
    ].mean()
)


# 6. Median comparison
print("\nMedian Support Metrics — Churned vs Active:")

print(
    support_churn.groupby("churn_flag")[
        [
            "total_tickets",
            "avg_resolution_hours",
            "avg_first_response_minutes",
            "avg_satisfaction",
            "escalated_tickets",
            "escalation_rate"
        ]
    ].median()
)


# 7. Satisfaction availability
print("\nSatisfaction Score Availability:")

print(
    support_tickets["satisfaction_score"]
    .isna()
    .value_counts()
)


# 8. Support priority vs escalation
print("\nPriority vs Escalation:")

print(
    pd.crosstab(
        support_tickets["priority"],
        support_tickets["escalation_flag"],
        normalize="index"
    ) * 100
)

print("=" * 70)
print("CUSTOMER LIFECYCLE & RETENTION ANALYSIS")
print("=" * 70)

# ---------------------------------------------------------
# 1. Subscription history per customer
# ---------------------------------------------------------

subscription_history = (
    subscriptions
    .groupby("account_id")
    .agg(
        total_subscriptions=("subscription_id", "count"),
        active_subscriptions=("churn_flag", lambda x: (~x).sum()),
        churned_subscriptions=("churn_flag", "sum"),
        total_mrr=("mrr_amount", "sum"),
        total_arr=("arr_amount", "sum"),
        total_upgrades=("upgrade_flag", "sum"),
        total_downgrades=("downgrade_flag", "sum"),
        auto_renew_subscriptions=("auto_renew_flag", "sum")
    )
    .reset_index()
)

print("\nSubscription History:")
print(subscription_history.describe())


# ---------------------------------------------------------
# 2. Churn events per customer
# ---------------------------------------------------------

churn_history = (
    churn_events
    .groupby("account_id")
    .agg(
        total_churn_events=("churn_event_id", "count"),
        total_refund=("refund_amount_usd", "sum"),
        reactivation_events=("is_reactivation", "sum"),
        upgrade_before_churn=("preceding_upgrade_flag", "sum"),
        downgrade_before_churn=("preceding_downgrade_flag", "sum")
    )
    .reset_index()
)

print("\nChurn Event History:")
print(churn_history.describe())


# ---------------------------------------------------------
# 3. Customer tenure
# ---------------------------------------------------------

today = accounts["signup_date"].max()

accounts_lifecycle = accounts.copy()

accounts_lifecycle["tenure_days"] = (
    today - accounts_lifecycle["signup_date"]
).dt.days

accounts_lifecycle["tenure_months"] = (
    accounts_lifecycle["tenure_days"] / 30.44
).round(1)

print("\nCustomer Tenure:")
print(
    accounts_lifecycle["tenure_months"].describe()
)


# ---------------------------------------------------------
# 4. Combine everything at customer level
# ---------------------------------------------------------

customer_lifecycle = (
    accounts_lifecycle
    .merge(subscription_history, on="account_id", how="left")
    .merge(churn_history, on="account_id", how="left")
)

# Customers without churn events get zero
customer_lifecycle[
    [
        "total_churn_events",
        "total_refund",
        "reactivation_events",
        "upgrade_before_churn",
        "downgrade_before_churn"
    ]
] = customer_lifecycle[
    [
        "total_churn_events",
        "total_refund",
        "reactivation_events",
        "upgrade_before_churn",
        "downgrade_before_churn"
    ]
].fillna(0)

print("\nCombined Customer Lifecycle Dataset:")
print(customer_lifecycle.shape)

print("\nSample:")
print(customer_lifecycle.head())


# ---------------------------------------------------------
# 5. Churn vs tenure
# ---------------------------------------------------------

print("\nTenure — Churned vs Active:")

print(
    customer_lifecycle.groupby("churn_flag")[
        ["tenure_days", "tenure_months"]
    ].agg(["mean", "median"])
)


# ---------------------------------------------------------
# 6. Churn vs subscription history
# ---------------------------------------------------------

print("\nSubscription History — Churned vs Active:")

print(
    customer_lifecycle.groupby("churn_flag")[
        [
            "total_subscriptions",
            "active_subscriptions",
            "churned_subscriptions",
            "total_upgrades",
            "total_downgrades",
            "auto_renew_subscriptions"
        ]
    ].mean()
)


# ---------------------------------------------------------
# 7. Revenue exposure by churn status
# ---------------------------------------------------------

print("\nRevenue Exposure — Churned vs Active:")

print(
    customer_lifecycle.groupby("churn_flag")[
        [
            "total_mrr",
            "total_arr"
        ]
    ].agg(["mean", "median", "sum"])
)


# ---------------------------------------------------------
# 8. Reactivation
# ---------------------------------------------------------

print("\nReactivation Analysis:")

print(
    "Customers with at least one reactivation:",
    (customer_lifecycle["reactivation_events"] > 0).sum()
)

print(
    "Total reactivation events:",
    int(customer_lifecycle["reactivation_events"].sum())
)


# ---------------------------------------------------------
# 9. Upgrade / downgrade behavior
# ---------------------------------------------------------

print("\nUpgrade / Downgrade Behavior:")

print(
    "Customers with upgrades:",
    (customer_lifecycle["total_upgrades"] > 0).sum()
)

print(
    "Customers with downgrades:",
    (customer_lifecycle["total_downgrades"] > 0).sum()
)

print(
    "Customers with both upgrades and downgrades:",
    (
        (customer_lifecycle["total_upgrades"] > 0) &
        (customer_lifecycle["total_downgrades"] > 0)
    ).sum()
)

print("=" * 70)
print("RETENTIONIQ CUSTOMER RISK SEGMENTATION")
print("=" * 70)

# ---------------------------------------------------------
# 1. Add usage metrics
# ---------------------------------------------------------

customer_risk = customer_lifecycle.merge(
    account_usage,
    on="account_id",
    how="left"
)

# Add support metrics
customer_risk = customer_risk.merge(
    account_support,
    on="account_id",
    how="left"
)

# Customers with no support tickets
support_numeric = [
    "total_tickets",
    "avg_resolution_hours",
    "avg_first_response_minutes",
    "avg_satisfaction",
    "escalated_tickets",
    "escalation_rate"
]

customer_risk[support_numeric] = customer_risk[support_numeric].fillna(0)


# ---------------------------------------------------------
# 2. Create risk signals
# ---------------------------------------------------------

# Low engagement = below median usage
usage_median = customer_risk["total_usage"].median()

customer_risk["low_engagement_flag"] = (
    customer_risk["total_usage"] < usage_median
)


# High support escalation
customer_risk["high_escalation_flag"] = (
    customer_risk["escalation_rate"] >
    customer_risk["escalation_rate"].median()
)


# Downgrade signal
customer_risk["downgrade_flag"] = (
    customer_risk["total_downgrades"] > 0
)


# High revenue customer
revenue_threshold = customer_risk["total_mrr"].quantile(0.75)

customer_risk["high_revenue_flag"] = (
    customer_risk["total_mrr"] >= revenue_threshold
)


# Longer-tenure customer
tenure_threshold = customer_risk["tenure_months"].median()

customer_risk["long_tenure_flag"] = (
    customer_risk["tenure_months"] >= tenure_threshold
)


# ---------------------------------------------------------
# 3. Calculate explainable risk score
# ---------------------------------------------------------

customer_risk["risk_score"] = (
    customer_risk["low_engagement_flag"].astype(int) +
    customer_risk["high_escalation_flag"].astype(int) +
    customer_risk["downgrade_flag"].astype(int) +
    customer_risk["high_revenue_flag"].astype(int) +
    customer_risk["long_tenure_flag"].astype(int)
)

# Existing churn status is NOT included in the score.
# The score is intended to prioritize active customers
# who may need retention attention.


# ---------------------------------------------------------
# 4. Create risk segments
# ---------------------------------------------------------

customer_risk["risk_segment"] = pd.cut(
    customer_risk["risk_score"],
    bins=[-1, 1, 3, 5],
    labels=[
        "Low Risk",
        "Medium Risk",
        "High Risk"
    ]
)


# ---------------------------------------------------------
# 5. Display segment distribution
# ---------------------------------------------------------

print("\nRisk Segment Distribution:")
print(customer_risk["risk_segment"].value_counts())


# ---------------------------------------------------------
# 6. Revenue exposure by segment
# ---------------------------------------------------------

print("\nRevenue by Risk Segment:")

print(
    customer_risk.groupby("risk_segment", observed=True)[
        ["total_mrr", "total_arr"]
    ].agg(["count", "mean", "sum"])
)


# ---------------------------------------------------------
# 7. Churn rate by risk segment
# ---------------------------------------------------------

print("\nChurn Rate by Risk Segment:")

risk_churn = (
    customer_risk
    .groupby("risk_segment", observed=True)["churn_flag"]
    .agg(["count", "sum", "mean"])
)

risk_churn["churn_rate_%"] = risk_churn["mean"] * 100
risk_churn = risk_churn.drop(columns=["mean"])

print(risk_churn)


# ---------------------------------------------------------
# 8. High-risk customers
# ---------------------------------------------------------

print("\nHigh-Risk Customer Summary:")

high_risk = customer_risk[
    customer_risk["risk_segment"] == "High Risk"
]

print("High-risk customers:", len(high_risk))

print(
    "High-risk MRR: $",
    round(high_risk["total_mrr"].sum(), 2)
)

print(
    "High-risk ARR: $",
    round(high_risk["total_arr"].sum(), 2)
)


# ---------------------------------------------------------
# 9. Active high-risk customers
# ---------------------------------------------------------

active_high_risk = customer_risk[
    (customer_risk["risk_segment"] == "High Risk") &
    (customer_risk["churn_flag"] == False)
]

print("\nActive High-Risk Customers:")
print("Count:", len(active_high_risk))

print(
    "MRR at risk: $",
    round(active_high_risk["total_mrr"].sum(), 2)
)

print(
    "ARR at risk: $",
    round(active_high_risk["total_arr"].sum(), 2)
)

print("=" * 70)
print("RISK SIGNAL VALIDATION")
print("=" * 70)

signals = [
    "low_engagement_flag",
    "high_escalation_flag",
    "downgrade_flag",
    "high_revenue_flag",
    "long_tenure_flag"
]

for signal in signals:

    print("\n" + "-" * 70)
    print(signal)

    result = (
        customer_risk
        .groupby("churn_flag")[signal]
        .mean() * 100
    )

    print("Active / Not Churned:", round(result.get(False, 0), 2), "%")
    print("Churned:", round(result.get(True, 0), 2), "%")

    if False in result.index and True in result.index:
        difference = result[True] - result[False]
        print("Difference:", round(difference, 2), "percentage points")


# Overall risk score comparison
print("\n" + "=" * 70)
print("OVERALL RISK SCORE")
print("=" * 70)

print(
    customer_risk.groupby("churn_flag")["risk_score"]
    .agg(["count", "mean", "median"])
)


# Risk score distribution
print("\nRisk Score Distribution:")

print(
    pd.crosstab(
        customer_risk["risk_score"],
        customer_risk["churn_flag"],
        normalize="index"
    ) * 100
)

print("=" * 70)
print("FINAL RETENTION PRIORITY FRAMEWORK")
print("=" * 70)

# ---------------------------------------------------------
# 1. Create validated retention priority score
# ---------------------------------------------------------

customer_risk["retention_priority_score"] = (
    customer_risk["long_tenure_flag"].astype(int) * 2 +
    customer_risk["high_escalation_flag"].astype(int) * 2 +
    customer_risk["high_revenue_flag"].astype(int) * 2
)


# ---------------------------------------------------------
# 2. Create priority segments
# ---------------------------------------------------------

customer_risk["retention_priority"] = pd.cut(
    customer_risk["retention_priority_score"],
    bins=[-1, 1, 3, 6],
    labels=[
        "Monitor",
        "Priority",
        "Critical"
    ]
)


# ---------------------------------------------------------
# 3. Distribution
# ---------------------------------------------------------

print("\nRetention Priority Distribution:")

print(
    customer_risk["retention_priority"]
    .value_counts()
    .sort_index()
)


# ---------------------------------------------------------
# 4. Revenue exposure
# ---------------------------------------------------------

print("\nRevenue Exposure by Priority:")

priority_revenue = (
    customer_risk
    .groupby("retention_priority", observed=True)
    [["total_mrr", "total_arr"]]
    .agg(["count", "mean", "sum"])
)

print(priority_revenue)


# ---------------------------------------------------------
# 5. Churn rate by priority
# ---------------------------------------------------------

print("\nHistorical Churn Rate by Priority:")

priority_churn = (
    customer_risk
    .groupby("retention_priority", observed=True)["churn_flag"]
    .agg(["count", "sum", "mean"])
)

priority_churn["churn_rate_%"] = (
    priority_churn["mean"] * 100
)

priority_churn = priority_churn.drop(columns=["mean"])

print(priority_churn)


# ---------------------------------------------------------
# 6. Active customers requiring attention
# ---------------------------------------------------------

active_priority = customer_risk[
    (customer_risk["churn_flag"] == False) &
    (customer_risk["retention_priority"].isin(
        ["Priority", "Critical"]
    ))
]

print("\nACTIVE CUSTOMERS REQUIRING RETENTION ATTENTION")

print("Customers:", len(active_priority))

print(
    "MRR exposure: $",
    round(active_priority["total_mrr"].sum(), 2)
)

print(
    "ARR exposure: $",
    round(active_priority["total_arr"].sum(), 2)
)


# ---------------------------------------------------------
# 7. Critical active customers
# ---------------------------------------------------------

critical_active = customer_risk[
    (customer_risk["churn_flag"] == False) &
    (customer_risk["retention_priority"] == "Critical")
]

print("\nCRITICAL ACTIVE CUSTOMERS")

print("Customers:", len(critical_active))

print(
    "MRR exposure: $",
    round(critical_active["total_mrr"].sum(), 2)
)

print(
    "ARR exposure: $",
    round(critical_active["total_arr"].sum(), 2)
)


# ---------------------------------------------------------
# 8. Top customers to investigate
# ---------------------------------------------------------

print("\nTOP 15 ACTIVE CUSTOMERS BY RETENTION PRIORITY:")

top_customers = (
    active_priority
    .sort_values(
        ["retention_priority_score", "total_mrr"],
        ascending=[False, False]
    )
    [
        [
            "account_id",
            "account_name",
            "industry",
            "plan_tier",
            "seats",
            "total_mrr",
            "tenure_months",
            "total_tickets",
            "escalation_rate",
            "retention_priority_score",
            "retention_priority"
        ]
    ]
    .head(15)
)

print(top_customers.to_string(index=False))

print("=" * 70)
print("BUILDING FINAL CUSTOMER ANALYTICS TABLE")
print("=" * 70)

# Start with the customer risk table
customer_analytics = customer_risk.copy()

# ---------------------------------------------------------
# Create business-friendly derived fields
# ---------------------------------------------------------

# Current customer status
customer_analytics["customer_status"] = np.where(
    customer_analytics["churn_flag"],
    "Churned",
    "Active"
)

# Auto-renew rate
customer_analytics["auto_renew_rate"] = (
    customer_analytics["auto_renew_subscriptions"] /
    customer_analytics["total_subscriptions"]
)

# Upgrade rate
customer_analytics["upgrade_rate"] = (
    customer_analytics["total_upgrades"] /
    customer_analytics["total_subscriptions"]
)

# Downgrade rate
customer_analytics["downgrade_rate"] = (
    customer_analytics["total_downgrades"] /
    customer_analytics["total_subscriptions"]
)

# Revenue per seat
customer_analytics["mrr_per_seat"] = (
    customer_analytics["total_mrr"] /
    customer_analytics["seats"]
)

# Support tickets per month of tenure
customer_analytics["tickets_per_tenure_month"] = (
    customer_analytics["total_tickets"] /
    customer_analytics["tenure_months"].replace(0, np.nan)
)

# ---------------------------------------------------------
# Retention reason
# ---------------------------------------------------------

def get_priority_reason(row):

    reasons = []

    if row["high_revenue_flag"]:
        reasons.append("High Revenue")

    if row["long_tenure_flag"]:
        reasons.append("Long Tenure")

    if row["high_escalation_flag"]:
        reasons.append("Support Escalation")

    if not reasons:
        return "No Major Risk Signal"

    return " + ".join(reasons)


customer_analytics["priority_reason"] = (
    customer_analytics.apply(get_priority_reason, axis=1)
)


# ---------------------------------------------------------
# Select final columns
# ---------------------------------------------------------

final_columns = [
    "account_id",
    "account_name",
    "industry",
    "country",
    "signup_date",
    "referral_source",
    "plan_tier",
    "seats",
    "is_trial",

    "customer_status",
    "tenure_days",
    "tenure_months",

    "total_subscriptions",
    "active_subscriptions",
    "churned_subscriptions",

    "total_mrr",
    "total_arr",
    "mrr_per_seat",

    "total_upgrades",
    "total_downgrades",
    "upgrade_rate",
    "downgrade_rate",
    "auto_renew_subscriptions",
    "auto_renew_rate",

    "usage_events",
    "total_usage",
    "total_duration_secs",
    "total_errors",
    "features_used",

    "total_tickets",
    "avg_resolution_hours",
    "avg_first_response_minutes",
    "avg_satisfaction",
    "escalated_tickets",
    "escalation_rate",

    "total_churn_events",
    "total_refund",
    "reactivation_events",

    "retention_priority_score",
    "retention_priority",
    "priority_reason"
]

customer_analytics = customer_analytics[final_columns]

print("\nFinal customer analytics shape:")
print(customer_analytics.shape)

print("\nColumns:")
print(customer_analytics.columns.tolist())

print("\nCustomer status:")
print(customer_analytics["customer_status"].value_counts())

print("\nRetention priority:")
print(customer_analytics["retention_priority"].value_counts())

print("\nPreview:")
display(customer_analytics.head())

import os

os.makedirs("02_Cleaned_Data", exist_ok=True)

customer_analytics.to_csv(
    "02_Cleaned_Data/customer_analytics.csv",
    index=False
)

print("Saved successfully:")
print("02_Cleaned_Data/customer_analytics.csv")

import os

os.makedirs("02_Cleaned_Data", exist_ok=True)

# Save cleaned source tables
accounts.to_csv(
    "02_Cleaned_Data/accounts_cleaned.csv",
    index=False
)

subscriptions.to_csv(
    "02_Cleaned_Data/subscriptions_cleaned.csv",
    index=False
)

feature_usage.to_csv(
    "02_Cleaned_Data/feature_usage_cleaned.csv",
    index=False
)

support_tickets.to_csv(
    "02_Cleaned_Data/support_tickets_cleaned.csv",
    index=False
)

churn_events.to_csv(
    "02_Cleaned_Data/churn_events_cleaned.csv",
    index=False
)

print("All cleaned source tables saved successfully!")

import os

print("=" * 70)
print("CLEANED DATA FILES")
print("=" * 70)

for file in sorted(os.listdir("02_Cleaned_Data")):
    file_path = os.path.join("02_Cleaned_Data", file)
    size_kb = os.path.getsize(file_path) / 1024

    print(f"{file:<35} {size_kb:,.1f} KB")

